name: Benchmark new formats

on:
  pull_request:
    paths:
      - 'waveform_benchmark/formats/**'
      
jobs:
  benchmark-new-formats:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r requirements.txt

      - name: Find new or modified benchmark files
        id: find-formats
        run: |
          git fetch origin main
          FILES=$(git diff --diff-filter=AM --name-only origin/main...HEAD 'waveform_benchmark/formats/*.py')
          echo "Format files: $FILES"
          echo "::set-output name=format_files::$FILES"

      - name: Run benchmark tests on new or modified format files
        if: steps.find-formats.outputs.format_files != ''
        run: |
          IFS=' ' read -ra FILES <<< "${{ steps.find-formats.outputs.format_files }}"
          for file in "${FILES[@]}"
          do
            # Skip base.py file
            if [[ "$file" == *"base.py" ]]; then
                echo "Skipping benchmark for $file"
                continue
            fi

            # Extract the module path from the file path
            MODULE_PATH=$(echo "$file" | sed 's/\//./g' | sed 's/\.py$//')

            # Find and list all classes in the module
            echo "Running benchmarks for classes in $MODULE_PATH"
            CLASSES=$(python3 -c "import sys; import inspect; from importlib import import_module; mod = import_module('$MODULE_PATH'); print(' '.join(cls for cls, obj in inspect.getmembers(mod, inspect.isclass) if obj.__module__ == mod.__name__))")
            IFS=' ' read -ra CLS <<< "$CLASSES"

            for cls in "${CLS[@]}"
            do
              CLASS_PATH="$MODULE_PATH.$cls"
              echo "Benchmarking $CLASS_PATH"
              ./waveform_benchmark.py -r ./data/waveforms/mimic_iv/waves/p100/p10079700/85594648/85594648 -f "$CLASS_PATH" > "benchmark_results_${cls}.txt"
            done
          done

      - name: Post results to pull request
        if: steps.find-formats.outputs.format_files != ''
        run: |
          RESULTS=""
          IFS=' ' read -ra FILES <<< "${{ steps.find-formats.outputs.format_files }}"
          for file in "${FILES[@]}"
          do
            FORMAT_CLASS=$(echo "$file" | grep -oP 'formats/\K(.*)(?=\.py)')
            RESULTS+="$FORMAT_CLASS:\n$(cat "benchmark_results_$FORMAT_CLASS.txt")\n"
          done
          echo -e "Benchmark results:\n\`\`\`\n$RESULTS\n\`\`\`" > final_results.txt

    #   - uses: unsplash/comment-on-pr@master
    #     if: steps.find-formats.outputs.format_files != ''
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     with:
    #       msg: "${{ readFile('final_results.txt') }}"
