name: Run style checks

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run code style check on changed files relative to PR base branch
        if: github.event_name == 'pull_request'
        run: |
          git rev-parse --verify ${{ github.event.pull_request.base.sha }}
          git diff -U0 ${{ github.event.pull_request.base.sha }} HEAD | \
              flake8 --diff | \
              perl -ne '
                print; if (/^([^:]+):(\d+):(\d+):/) {
                  $path = $1; $line = $2; $col = $3;
                  open F, $path or die;
                  print "\n";
                  while (<F>) {
                    next if $. < $line - 2;
                    print " $_";
                    if ($. == $line) { print " " x $col . "^\n\n"; last; }
                  }
                  close F;
                  $status = 1;
                }
                END { exit $status }'

      - name: Run code style check on the entire codebase for push events
        if: github.event_name == 'push'
        run: |
          flake8 .
