name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
    # - name: Install this repo
    #   run: python -m pip install .
    - name: Download a couple of files
      run: |
        # Download data to a tests/data/ directory
        wget https://physionet.org/files/mimic3wdb-matched/1.0/p00/p000030/3524877_0001.hea -P tests/data/
    - name: Run tests
      run: |
        pytest -v
